# Generated by Django 3.1.5 on 2021-02-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_remove_analysis_word_cloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='score',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
