# Generated by Django 3.1.5 on 2021-02-06 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_analysis_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='score',
        ),
    ]
