# Generated by Django 3.1.5 on 2021-02-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_remove_analysis_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='score',
            field=models.CharField(default='0,0', max_length=300, verbose_name='0,0'),
            preserve_default=False,
        ),
    ]
