# Generated by Django 3.1.5 on 2021-02-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_analysis_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='title',
            field=models.CharField(default='ahmet', max_length=500, verbose_name='ahmet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysis',
            name='limit',
            field=models.IntegerField(verbose_name='How many posts to visualize'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='topic',
            field=models.CharField(max_length=300, verbose_name='Please enter a valid subreddit name(e.g. Coronavirus , politics , news'),
        ),
    ]
